usb_hanbetsu/usb_hanbetsu/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
#usbaiの中のurls.pyをルーティングに組み込む
    path("usbai/",include("usbai.urls")),
]

usb_hanbetsu/usbai/urls.py
from django.urls import path
from . import views

app_name="usbai"
urlpatterns=[
    path("",views.index,name="index"),
    path("predict/",views.predict,name="predict"),
]

usb_hanbetsu/usbai/models.py
from django.db import models
import numpy as np
import sys
import tensorflow.compat.v1 as tf
from tensorflow.keras.models import load_model
from PIL import Image
import io,base64

# Create your models here.
graph=tf.get_default_graph()
class Photo(models.Model):
    image=models.ImageField(upload_to="photos")

    IMAGE_SIZE=128 #画像サイズ
    MODEL_PATH="./usbai/ml_models/my_model_epoch45.h5"
    imagename=['Micro-USB-TypeB-2.0', 'Micro-USB-TypeB-3.0', 'Mini-USB-TypeB', 'USB-TypeA', 'USB-TypeC'] #あとで入れろ
    image_len=len(imagename)

    def predict(self):
        model=None
        global graph#毎回同じモデルのセッションに投入して推論可能にする。
        with graph.as_default():
            model=load_model(self.MODEL_PATH)

            img_data=self.image.read()
            img_bin=io.BytesIO(img_data)

            image=Image.open(img_bin)
            image=image.convert("RGB")
            image=image.resize((self.IMAGE_SIZE,self.IMAGE_SIZE))
            data=np.asarray(image)/255.0
            X=[]
            X.append(data)
            X=np.array(X)

            result=model.predict([X])[0]
            predicted=result.argmax()
            percentage=int(result[predicted]*100)

            return self.imagename[predicted],percentage
        
    def image_src(self):
        with self.image.open() as img:
            base64_img=base64.b64encode(img.read()).decode()

            return "data:"+img.file.content_type+";base64,"+base64_img

usb_hanbetsu/usbai/forms.py
from django import forms
from django.core.files.storage import default_storage

class PhotoForm(forms.Form):
    image=forms.ImageField(widget=forms.FileInput(attrs={"class":"custom-file-input"}))

usb_hanbetsu/usbai/views.py
from django.shortcuts import redirect
from django.http import HttpResponse
from django.template import loader
from .forms import PhotoForm
from .models import Photo

result_url = {'Micro-USB-TypeB-2.0':'https://www.google.com/search?q=micro+usb+type-b+2.0+cable',
              'Micro-USB-TypeB-3.0':'https://www.google.com/search?q=micro+usb+type-b+3.0+cable',
              'Mini-USB-TypeB':'https://www.google.com/search?q=mini+usb+type-b', 
              'USB-TypeA':'https://www.google.com/search?q=USB+cable+type-A', 
              'USB-TypeC':'https://www.google.com/search?q=usb+type-c'}

def index(request):
    template=loader.get_template("usbai/index.html")
    form = PhotoForm()
    filename_save = '*現在ファイル名は表示されません'
    context={"form":form, "filename_save": filename_save}
    return HttpResponse(template.render(context,request))

def predict(request):
    if not request.method=="POST":
        return redirect("usbai:index")
    form=PhotoForm(request.POST,request.FILES)
    if not form.is_valid():
        raise ValueError("Formが不正です")

    photo=Photo(image=form.cleaned_data["image"])
    predicted,percentage=photo.predict()

    template=loader.get_template("usbai/result.html")

    context={
        "photo_name":photo.image.name,
        "photo_data":photo.image_src(),
        "predicted":predicted,
        "percentage":percentage,
        "result_url":result_url[predicted],
    }
    return HttpResponse(template.render(context,request))

usb_hanbetsu/templates/usbai/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  {% load bootstrap4 %}
  {% bootstrap_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  {% bootstrap_javascript jquery="full" %}
  <title>{% block title %}Ur Name {% endblock %}</title>
</head>
<!--hrefでstatic/css/style.cssを参照できる(setting.pyのSTATICFILES_URL)-->
<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Features</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
          <div class="title-method">
            <p class="navber-brand">Ur Name</p>
          </div>
        </ul>
      </div>
    </nav>
  </header>
  <div class="container">
    {% block content %}{% endblock %}
  </div>
</body>
</html>

usb_hanbetsu/templates/usbai/index.html
{% extends "usbai/base.html" %}
{% block title %}Ur Name(Home){% endblock %}

{% block content %}
<div class="alert">
    <td><h1 class="mt-4 mb-5 boder-top">AIがUSBポートの規格とそこにあうケーブルを教えます</h1></td>
  <br>
  <p class="custom-class">画像ファイルを選択して推定ボタンを押してください。</p>
  <br>
  <form action="{% url 'usbai:predict' %}"  method="post" class="form" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group">
    <div class="custom-file">
      {{ form.image }}
      <label class="custom-file-label" for="customFile">
        推定したいファイルを選択してください。
      </label>
      {% if filename_save %}
          {{ filename_save }}
      {% endif %}
    </div>
  </div>
  <br>
  <div class="btn-wrapper">
  <button type="submit" class="btn btn-secondary btn-lg btn-block">推定スタート!</button>
  </div>
  </form>
</div>
<br></br>

{% endblock %}

usb_hanbetsu/templates/usbai/result.html
{% extends "usbai/base.html" %}
{% load static %}
{% block title %}Ur Name (Result){% endblock %}

{% block content %}
<div class="result">
  <h4 class="mt-4 mb-5 boder-bottom">画像推定結果</h4>
  <table class="table">
      <p class="body-wrapper">ファイル名:{{photo_name}}</p>

      <h2>画像ファイル<h2>
      <img class="preview-img" src={{photo_data}}></img>

      <p>規格名:{{predicted}}</p>
      <p>推定確率:{{percentage}} %</p>

      <p>このポートに刺さる端子</p>
      <img class="preview-img" src="{% static 'img/' %}{{predicted}}.jpg"> </img>
      <p><a href={{ result_url }} target="_blank" rel="noopener noreferrer">この端子のケーブル欲しい人はこちら！(Google検索結果)</a></p>
      
  </table>
  <br>

  <a href="{% url 'usbai:index' %}" class="btn btn-primary btn-lg btn-block">選択メニューに戻る</a>

</div>
{% endblock %}